name: cleanBib
channels:
  - conda-forge
dependencies:
  - python=3.9.10
  - pip
  - pip:
    - pybtex==0.24.0
    - numpy==1.19.5
    - bibtexparser==1.2.0
    - pandas==1.4.2
    - pylatexenc==2.10
    - sos
    - sos-notebook
    - habanero==1.2.0
    - ethnicolr==0.8.1
    - matplotlib==3.5.1
    - seaborn==0.11.2
    - scipy==1.8.0
    - h5py==3.1.0
    - oauthlib==3.2.0
    - rsa==4.8
    - Keras==2.8.0
    - tensorflow==2.5.2
    - protobuf==3.20.1
    - nbgitpuller
    - sphinx-gallery
    - csv
    - subprocess
    - os
    - re
    - tqdm
    - json
    - pickle
    - urllib